from flask import Blueprint, request, jsonify
# For real AI - integrate Gemini API here

ai_bp = Blueprint('ai', __name__)

@ai_bp.route('/generate-resume', methods=['POST'])
def generate_resume():
    profile = request.get_json()
    # Call Gemini API using profile, return fake result for now
    return jsonify({
        "summary": "Professional summary generated by AI...",
        "skills": "Python, React, SQL",
        "projects": "Project A, Project B",
        "achievements": "Won Hackathon"
    })